AWSTemplateFormatVersion: '2010-09-09'
Description: 'ML Infrastructure Stack for AI Image Detection'

Parameters:
  ProjectName:
    Type: String
    Default: ai-detection
    Description: Name of the project
  
  EnvironmentName:
    Type: String
    Default: training
    AllowedValues:
      - training
      - inference
      - development
    Description: Environment type

Resources:
  # S3 Buckets
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-data-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName
  
  ModelArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-models-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldModels
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  
  # IAM Role for ML Instances
  MLInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ml-instance-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - sagemaker.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'
                  - !GetAtt ModelArtifactsBucket.Arn
                  - !Sub '${ModelArtifactsBucket.Arn}/*'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  
  MLInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-ml-instance-profile'
      Roles:
        - !Ref MLInstanceRole
  
  # Security Group
  MLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-ml-sg'
      GroupDescription: Security group for ML training instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 6006
          ToPort: 6006
          CidrIp: 0.0.0.0/0
          Description: TensorBoard
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0
          Description: Jupyter Notebook
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  
  # CloudWatch Dashboard
  MLDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-training-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  [ "ML/ImageDetection", "train_loss", { "stat": "Average" } ],
                  [ ".", "val_loss", { "stat": "Average" } ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Training Loss"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  [ "ML/ImageDetection", "train_acc", { "stat": "Average" } ],
                  [ ".", "val_acc", { "stat": "Average" } ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Model Accuracy"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  [ "ML/Costs", "TrainingCost", { "stat": "Sum" } ]
                ],
                "period": 3600,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Training Costs"
              }
            }
          ]
        }

Outputs:
  DataBucketName:
    Description: Name of the S3 bucket for training data
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${ProjectName}-data-bucket'
  
  ModelBucketName:
    Description: Name of the S3 bucket for model artifacts
    Value: !Ref ModelArtifactsBucket
    Export:
      Name: !Sub '${ProjectName}-model-bucket'
  
  SecurityGroupId:
    Description: ID of the ML security group
    Value: !Ref MLSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-sg-id'
  
  InstanceProfileArn:
    Description: ARN of the ML instance profile
    Value: !GetAtt MLInstanceProfile.Arn
    Export:
      Name: !Sub '${ProjectName}-instance-profile-arn'